name = "katalog-barang"
workers_dev = true
compatibility_date = "2025-06-23"
main = "worker/index.js"

kv_namespaces = [
  { binding = "KATALOG", id = "552f4d9d18164051a77ad2e4ba52a43c" },
  { binding = "AUTH_STORE", id = "3b68a7b6d04444bc9cdbced5926a62d7" }
]
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true





